spring.application.name=spring-boot-909-lec9

spring.datasource.driver-class-name= oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=hr
spring.datasource.password=hr123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
